apiVersion: apps/v1
kind: Deployment
metadata:
  name: abdi-test
  namespace: production  
spec:
  replicas: 1
  revisionHistoryLimit: 4
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 0
     maxSurge: 50%
  selector:
    matchLabels:
      app: abdi-test
  template:
    metadata:
      labels:
        app: abdi-test
        env: production 
      annotations:
        configmap.reloader.stakater.com/reload: "production-abdi-configmap"
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: production-abdi-configmap
        name: abdi-test
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
            requests:
               cpu: "100m"
               memory: "150Mi"
            limits:
               cpu: "400m"
               memory: "600Mi"
